services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: txd-backend
    environment:
      # === App configuration ===
      APP_JWT_SECRET: "6a3d5f0b9c1e2a4c6e8f1029384756aa6b7c8d9e0f1a2b3c4d5e6f708192a3bc" # 32+ bytes
      APP_SEED_ENABLED: "true"          # seed demo users + transactions
      APP_CORS_ALLOWED_ORIGINS: "http://localhost:5173"
      APP_SWAGGER_BYPASS: "true"        # you enabled Option B earlier
      # === Spring/H2 ===
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      # Optional: turn on H2 console
      # SPRING_H2_CONSOLE_ENABLED: "true"
      APP_CORS_ALLOWED_ORIGINS: "http://localhost:8082,http://localhost:5173"
      APP_CORS_ALLOWED_HEADERS: "Authorization,Content-Type"
      APP_CORS_ALLOWED_METHODS: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      APP_SWAGGER_BYPASS: "true"
      APP_SEED_ENABLED: "true"      
    ports:
      - "8081:8080"
    # healthcheck helpful for CI
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # The browser must call the backend via localhost:8081
        VITE_API_URL: "http://localhost:8081/api/v1"
        VITE_AUTH_URL: "http://localhost:8081/api/auth"
    container_name: txd-frontend
    ports:
      - "8082:80"
    depends_on:
      - backend


