server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:portal;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    time-zone: UTC

logging:
  level:
    root: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  cors:
    allowed-origins: "http://localhost:5173"   # exact origin of Vite dev server
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-headers: "Authorization,Content-Type"
    allow-credentials: true
  seed:
    enabled: true
  jwt:
    secret: ${APP_JWT_SECRET:change-me-super-secret-256-bit-key}
  swagger:
    bypass: true


